name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint via python-black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint (via python-black)
        uses: psf/black@stable